spring.application.name=ms-professor

server.port=8086

# Configuração do Banco de Dados local
spring.datasource.url=jdbc:postgresql://localhost:5432/ms_professor
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

# Evita que o Eureka trave o console enquanto o seu colega não sobe o Discovery Server
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true